In [1]:
import pandas as pd
import numpy as np

In [2]:
merged_df = pd.read_pickle("./data/processed/merged_dataset.pkl")
merged_df.head(10)

,question,topic,cat,source_sentence,atomic-fact,label,evidence_passages
0,Tell me a bio of Marianne McAndrew.,Marianne McAndrew,"[very rare, North America]",Marianne McAndrew is an American actress and s...,Marianne McAndrew is an American.,NS,[<s>Marianne McAndrew Marianne Christine McAnd...
1,Tell me a bio of Marianne McAndrew.,Marianne McAndrew,"[very rare, North America]",Marianne McAndrew is an American actress and s...,Marianne McAndrew is an actress.,S,[<s>Marianne McAndrew Marianne Christine McAnd...
2,Tell me a bio of Marianne McAndrew.,Marianne McAndrew,"[very rare, North America]",Marianne McAndrew is an American actress and s...,Marianne McAndrew is a singer.,NS,[<s>Marianne McAndrew Marianne Christine McAnd...
3,Tell me a bio of Marianne McAndrew.,Marianne McAndrew,"[very rare, North America]",Marianne McAndrew is an American actress and s...,"Marianne McAndrew was born on November 21, 1942.",NS,[<s>Marianne McAndrew Marianne Christine McAnd...
4,Tell me a bio of Marianne McAndrew.,Marianne McAndrew,"[very rare, North America]",Marianne McAndrew is an American actress and s...,Marianne McAndrew was born in Cleveland.,NS,[<s>Marianne McAndrew Marianne Christine McAnd...
5,Tell me a bio of Marianne McAndrew.,Marianne McAndrew,"[very rare, North America]",Marianne McAndrew is an American actress and s...,Cleveland is in Ohio.,NS,[<s>Marianne McAndrew Marianne Christine McAnd...
6,Tell me a bio of Gerhard Fischer (inventor).,Gerhard Fischer (inventor),"[very rare, North America]",Gerhard Fischer is an inventor and entrepreneu...,Gerhard Fischer is an inventor.,S,"[ the hand-held metal detector is disputed, th..."
7,Tell me a bio of Gerhard Fischer (inventor).,Gerhard Fischer (inventor),"[very rare, North America]",Gerhard Fischer is an inventor and entrepreneu...,Gerhard Fischer is an entrepreneur.,S,"[ the hand-held metal detector is disputed, th..."
8,Tell me a bio of Gerhard Fischer (inventor).,Gerhard Fischer (inventor),"[very rare, North America]",Gerhard Fischer is an inventor and entrepreneu...,Gerhard Fischer is best known for inventing a ...,S,[<s>Gerhard Fischer (inventor) Gerhard Julius ...
9,Tell me a bio of Gerhard Fischer (inventor).,Gerhard Fischer (inventor),"[very rare, North America]",Gerhard Fischer is an inventor and entrepreneu...,"Gerhard Fischer invented the first handheld, b...",S,"[ the hand-held metal detector is disputed, th..."

In [3]:
merged_df.drop(columns=['cat'],inplace=True)
merged_df.head(10)

,question,topic,source_sentence,atomic-fact,label,evidence_passages
0,Tell me a bio of Marianne McAndrew.,Marianne McAndrew,Marianne McAndrew is an American actress and s...,Marianne McAndrew is an American.,NS,[<s>Marianne McAndrew Marianne Christine McAnd...
1,Tell me a bio of Marianne McAndrew.,Marianne McAndrew,Marianne McAndrew is an American actress and s...,Marianne McAndrew is an actress.,S,[<s>Marianne McAndrew Marianne Christine McAnd...
2,Tell me a bio of Marianne McAndrew.,Marianne McAndrew,Marianne McAndrew is an American actress and s...,Marianne McAndrew is a singer.,NS,[<s>Marianne McAndrew Marianne Christine McAnd...
3,Tell me a bio of Marianne McAndrew.,Marianne McAndrew,Marianne McAndrew is an American actress and s...,"Marianne McAndrew was born on November 21, 1942.",NS,[<s>Marianne McAndrew Marianne Christine McAnd...
4,Tell me a bio of Marianne McAndrew.,Marianne McAndrew,Marianne McAndrew is an American actress and s...,Marianne McAndrew was born in Cleveland.,NS,[<s>Marianne McAndrew Marianne Christine McAnd...
5,Tell me a bio of Marianne McAndrew.,Marianne McAndrew,Marianne McAndrew is an American actress and s...,Cleveland is in Ohio.,NS,[<s>Marianne McAndrew Marianne Christine McAnd...
6,Tell me a bio of Gerhard Fischer (inventor).,Gerhard Fischer (inventor),Gerhard Fischer is an inventor and entrepreneu...,Gerhard Fischer is an inventor.,S,"[ the hand-held metal detector is disputed, th..."
7,Tell me a bio of Gerhard Fischer (inventor).,Gerhard Fischer (inventor),Gerhard Fischer is an inventor and entrepreneu...,Gerhard Fischer is an entrepreneur.,S,"[ the hand-held metal detector is disputed, th..."
8,Tell me a bio of Gerhard Fischer (inventor).,Gerhard Fischer (inventor),Gerhard Fischer is an inventor and entrepreneu...,Gerhard Fischer is best known for inventing a ...,S,[<s>Gerhard Fischer (inventor) Gerhard Julius ...
9,Tell me a bio of Gerhard Fischer (inventor).,Gerhard Fischer (inventor),Gerhard Fischer is an inventor and entrepreneu...,"Gerhard Fischer invented the first handheld, b...",S,"[ the hand-held metal detector is disputed, th..."

In [32]:
print(merged_df.iloc[20]["evidence_passages"])

['<s>Taral Hicks Taral Hicks (born September 21, 1974) is an American actress and singer. Hicks is best known for her acting in such films as 1993\'s American crime drama film "A Bronx Tale" and her singing in such work as her 1997 debut studio album "This Time" which peaked at No. 4 on "Billboard" Bubbling Under Hot 100 Singles. Raised in Teaneck, New Jersey, Hicks graduated from Teaneck High School in 1994.</s><s>Career.</s><s>Career.:Acting. Hicks began her film career with a role in the critically acclaimed 1993 film, "A Bronx Tale". Her subsequent film roles were small: 1995\'s "Just Cause" with Sean Connery and Laurence Fishburne, and 1996\'s "Educating Matt Waters" and "The Preacher\'s Wife" with Whitney Houston. She appeared in the movie "Belly" in 1998. In 2000, she appeared on screen in the short film, "Are You Cinderella?", with actor Wood Harris. Her later film roles were in independent films such as 2005\'s "The Salon", with Vivica A. Fox, Dondre Whitfield, and Darrin Henson; 2006\'s "Forbidden Fruits" with', '", a remake of the classic R&B hit by Deniece Williams, was released. Featuring a black-and-white music video directed by Hype Williams, the single charted well on the R&B chart. After collaborating on the video for "Silly", Williams cast Hicks as in his directorial film debut, 1998\'s "Belly", as Keisha, DMX\'s girlfriend. The video for "Silly" appeared in one of the film\'s scenes. Hicks has expressed interest in pursuing a career in gospel music.</s><s>Personal life. Hicks is a 1993 graduate of Grace Dodge Vocational High School in the Bronx, New York. She is the younger sister of actress and singer D\'atra Hicks. In 1999, Hicks began dating Loren Dawson, and the couple married in 2001.</s><s>Discography.</s><s>Discography.:Singles. - Soundtracks - 1996: "The Associate" (on "Yes We Can Can" with Chantay Savage, LaShanda Reese and The Pointer Sisters)</s>', ' Ella Joyce, Fredro Starr, and R&B singer Keith Sweat; 2007\'s "Humenetomy"; and 2010\'s "Ex$pendable". Hicks featured in the HBO television series "Subway Stories" in 1997. Two guest roles followed: 2002\'s "100 Centre Street" in the episode titled "Fathers", and a 2003 episode of "Soul Food: The Series" titled "The New Math". Hicks co-starred in the musical stage play Tyler Perry\'s "Aunt Bam\'s Place" with Paris Bennett, Cassi Davis, Jeffrey Lewis, and Melonie Daniels. It had a 3-day run beginning August 30, 2011 in Atlanta, Georgia (Cobb Energy Center) and was filmed for a DVD release on June 12, 2012.</s><s>Career.:Music. In 1995, Hicks signed a deal with Motown Records and released an album titled "This Time". The single "Ooh, Ooh Baby", written by and featuring Missy Elliott, charted on the Billboard R&B singles chart. However, the lead single intended to debut her singing career was "Distant Lover", an uptempo track produced by Teddy Riley. The album did not take off until the second single, "Silly']

In [33]:
senteces = ""
count =0
index = 20
for i in "".join(merged_df.iloc[index]["evidence_passages"]).split("</s><s>"):
    count+=1
    if count == 1:
        i = i.strip("<s> ")
        if i.startswith(merged_df.iloc[index]["topic"]+ " "):
            i = i[len(merged_df.iloc[index]["topic"]):].strip()
    else:
        i = " ".join(i.split(" ")[1::])
    if i == "":
        continue
    print(f"{count} {i}")
    senteces += i

1 Taral Hicks (born September 21, 1974) is an American actress and singer. Hicks is best known for her acting in such films as 1993's American crime drama film "A Bronx Tale" and her singing in such work as her 1997 debut studio album "This Time" which peaked at No. 4 on "Billboard" Bubbling Under Hot 100 Singles. Raised in Teaneck, New Jersey, Hicks graduated from Teaneck High School in 1994.
3 Hicks began her film career with a role in the critically acclaimed 1993 film, "A Bronx Tale". Her subsequent film roles were small: 1995's "Just Cause" with Sean Connery and Laurence Fishburne, and 1996's "Educating Matt Waters" and "The Preacher's Wife" with Whitney Houston. She appeared in the movie "Belly" in 1998. In 2000, she appeared on screen in the short film, "Are You Cinderella?", with actor Wood Harris. Her later film roles were in independent films such as 2005's "The Salon", with Vivica A. Fox, Dondre Whitfield, and Darrin Henson; 2006's "Forbidden Fruits" with", a remake of the classic R&B hit by Deniece Williams, was released. Featuring a black-and-white music video directed by Hype Williams, the single charted well on the R&B chart. After collaborating on the video for "Silly", Williams cast Hicks as in his directorial film debut, 1998's "Belly", as Keisha, DMX's girlfriend. The video for "Silly" appeared in one of the film's scenes. Hicks has expressed interest in pursuing a career in gospel music.
4 life. Hicks is a 1993 graduate of Grace Dodge Vocational High School in the Bronx, New York. She is the younger sister of actress and singer D'atra Hicks. In 1999, Hicks began dating Loren Dawson, and the couple married in 2001.
6 - Soundtracks - 1996: "The Associate" (on "Yes We Can Can" with Chantay Savage, LaShanda Reese and The Pointer Sisters)</s> Ella Joyce, Fredro Starr, and R&B singer Keith Sweat; 2007's "Humenetomy"; and 2010's "Ex$pendable". Hicks featured in the HBO television series "Subway Stories" in 1997. Two guest roles followed: 2002's "100 Centre Street" in the episode titled "Fathers", and a 2003 episode of "Soul Food: The Series" titled "The New Math". Hicks co-starred in the musical stage play Tyler Perry's "Aunt Bam's Place" with Paris Bennett, Cassi Davis, Jeffrey Lewis, and Melonie Daniels. It had a 3-day run beginning August 30, 2011 in Atlanta, Georgia (Cobb Energy Center) and was filmed for a DVD release on June 12, 2012.
7 In 1995, Hicks signed a deal with Motown Records and released an album titled "This Time". The single "Ooh, Ooh Baby", written by and featuring Missy Elliott, charted on the Billboard R&B singles chart. However, the lead single intended to debut her singing career was "Distant Lover", an uptempo track produced by Teddy Riley. The album did not take off until the second single, "Silly

In [34]:
print(senteces)

Taral Hicks (born September 21, 1974) is an American actress and singer. Hicks is best known for her acting in such films as 1993's American crime drama film "A Bronx Tale" and her singing in such work as her 1997 debut studio album "This Time" which peaked at No. 4 on "Billboard" Bubbling Under Hot 100 Singles. Raised in Teaneck, New Jersey, Hicks graduated from Teaneck High School in 1994.Hicks began her film career with a role in the critically acclaimed 1993 film, "A Bronx Tale". Her subsequent film roles were small: 1995's "Just Cause" with Sean Connery and Laurence Fishburne, and 1996's "Educating Matt Waters" and "The Preacher's Wife" with Whitney Houston. She appeared in the movie "Belly" in 1998. In 2000, she appeared on screen in the short film, "Are You Cinderella?", with actor Wood Harris. Her later film roles were in independent films such as 2005's "The Salon", with Vivica A. Fox, Dondre Whitfield, and Darrin Henson; 2006's "Forbidden Fruits" with", a remake of the classic R&B hit by Deniece Williams, was released. Featuring a black-and-white music video directed by Hype Williams, the single charted well on the R&B chart. After collaborating on the video for "Silly", Williams cast Hicks as in his directorial film debut, 1998's "Belly", as Keisha, DMX's girlfriend. The video for "Silly" appeared in one of the film's scenes. Hicks has expressed interest in pursuing a career in gospel music.life. Hicks is a 1993 graduate of Grace Dodge Vocational High School in the Bronx, New York. She is the younger sister of actress and singer D'atra Hicks. In 1999, Hicks began dating Loren Dawson, and the couple married in 2001.- Soundtracks - 1996: "The Associate" (on "Yes We Can Can" with Chantay Savage, LaShanda Reese and The Pointer Sisters)</s> Ella Joyce, Fredro Starr, and R&B singer Keith Sweat; 2007's "Humenetomy"; and 2010's "Ex$pendable". Hicks featured in the HBO television series "Subway Stories" in 1997. Two guest roles followed: 2002's "100 Centre Street" in the episode titled "Fathers", and a 2003 episode of "Soul Food: The Series" titled "The New Math". Hicks co-starred in the musical stage play Tyler Perry's "Aunt Bam's Place" with Paris Bennett, Cassi Davis, Jeffrey Lewis, and Melonie Daniels. It had a 3-day run beginning August 30, 2011 in Atlanta, Georgia (Cobb Energy Center) and was filmed for a DVD release on June 12, 2012.In 1995, Hicks signed a deal with Motown Records and released an album titled "This Time". The single "Ooh, Ooh Baby", written by and featuring Missy Elliott, charted on the Billboard R&B singles chart. However, the lead single intended to debut her singing career was "Distant Lover", an uptempo track produced by Teddy Riley. The album did not take off until the second single, "Silly

In [20]:
count =0
for i in "".join(merged_df.iloc[index]["evidence_passages"]).split("</s><s>"):
    count+=1
    print(f"{count} {i}")

1 <s>Taral Hicks Taral Hicks (born September 21, 1974) is an American actress and singer. Hicks is best known for her acting in such films as 1993's American crime drama film "A Bronx Tale" and her singing in such work as her 1997 debut studio album "This Time" which peaked at No. 4 on "Billboard" Bubbling Under Hot 100 Singles. Raised in Teaneck, New Jersey, Hicks graduated from Teaneck High School in 1994.
2 Career.
3 Career.:Acting. Hicks began her film career with a role in the critically acclaimed 1993 film, "A Bronx Tale". Her subsequent film roles were small: 1995's "Just Cause" with Sean Connery and Laurence Fishburne, and 1996's "Educating Matt Waters" and "The Preacher's Wife" with Whitney Houston. She appeared in the movie "Belly" in 1998. In 2000, she appeared on screen in the short film, "Are You Cinderella?", with actor Wood Harris. Her later film roles were in independent films such as 2005's "The Salon", with Vivica A. Fox, Dondre Whitfield, and Darrin Henson; 2006's "Forbidden Fruits" with", a remake of the classic R&B hit by Deniece Williams, was released. Featuring a black-and-white music video directed by Hype Williams, the single charted well on the R&B chart. After collaborating on the video for "Silly", Williams cast Hicks as in his directorial film debut, 1998's "Belly", as Keisha, DMX's girlfriend. The video for "Silly" appeared in one of the film's scenes. Hicks has expressed interest in pursuing a career in gospel music.
4 Personal life. Hicks is a 1993 graduate of Grace Dodge Vocational High School in the Bronx, New York. She is the younger sister of actress and singer D'atra Hicks. In 1999, Hicks began dating Loren Dawson, and the couple married in 2001.
5 Discography.
6 Discography.:Singles. - Soundtracks - 1996: "The Associate" (on "Yes We Can Can" with Chantay Savage, LaShanda Reese and The Pointer Sisters)</s> Ella Joyce, Fredro Starr, and R&B singer Keith Sweat; 2007's "Humenetomy"; and 2010's "Ex$pendable". Hicks featured in the HBO television series "Subway Stories" in 1997. Two guest roles followed: 2002's "100 Centre Street" in the episode titled "Fathers", and a 2003 episode of "Soul Food: The Series" titled "The New Math". Hicks co-starred in the musical stage play Tyler Perry's "Aunt Bam's Place" with Paris Bennett, Cassi Davis, Jeffrey Lewis, and Melonie Daniels. It had a 3-day run beginning August 30, 2011 in Atlanta, Georgia (Cobb Energy Center) and was filmed for a DVD release on June 12, 2012.
7 Career.:Music. In 1995, Hicks signed a deal with Motown Records and released an album titled "This Time". The single "Ooh, Ooh Baby", written by and featuring Missy Elliott, charted on the Billboard R&B singles chart. However, the lead single intended to debut her singing career was "Distant Lover", an uptempo track produced by Teddy Riley. The album did not take off until the second single, "Silly

In [31]:
int(" 2012")

2012

In [35]:
import re

index = 20
row = merged_df.iloc[index]
topic = row["topic"]

sentences = ""
# split into passages (this splits passages, NOT sentences — see Bug 3)
pieces = "".join(row["evidence_passages"]).split("</s><s>")

for n, piece in enumerate(pieces):
    piece = re.sub(r"</?s>", "", piece).strip()      # Bug 1 fix: remove tags properly
    if piece.startswith(topic + " "):                # strip repeated title, for every piece
        piece = piece[len(topic):].strip()
    if piece == "":
        continue
    print(f"{n} {piece}")
    sentences += piece + " "                          # space between pieces

0 Taral Hicks (born September 21, 1974) is an American actress and singer. Hicks is best known for her acting in such films as 1993's American crime drama film "A Bronx Tale" and her singing in such work as her 1997 debut studio album "This Time" which peaked at No. 4 on "Billboard" Bubbling Under Hot 100 Singles. Raised in Teaneck, New Jersey, Hicks graduated from Teaneck High School in 1994.
1 Career.
2 Career.:Acting. Hicks began her film career with a role in the critically acclaimed 1993 film, "A Bronx Tale". Her subsequent film roles were small: 1995's "Just Cause" with Sean Connery and Laurence Fishburne, and 1996's "Educating Matt Waters" and "The Preacher's Wife" with Whitney Houston. She appeared in the movie "Belly" in 1998. In 2000, she appeared on screen in the short film, "Are You Cinderella?", with actor Wood Harris. Her later film roles were in independent films such as 2005's "The Salon", with Vivica A. Fox, Dondre Whitfield, and Darrin Henson; 2006's "Forbidden Fruits" with", a remake of the classic R&B hit by Deniece Williams, was released. Featuring a black-and-white music video directed by Hype Williams, the single charted well on the R&B chart. After collaborating on the video for "Silly", Williams cast Hicks as in his directorial film debut, 1998's "Belly", as Keisha, DMX's girlfriend. The video for "Silly" appeared in one of the film's scenes. Hicks has expressed interest in pursuing a career in gospel music.
3 Personal life. Hicks is a 1993 graduate of Grace Dodge Vocational High School in the Bronx, New York. She is the younger sister of actress and singer D'atra Hicks. In 1999, Hicks began dating Loren Dawson, and the couple married in 2001.
4 Discography.
5 Discography.:Singles. - Soundtracks - 1996: "The Associate" (on "Yes We Can Can" with Chantay Savage, LaShanda Reese and The Pointer Sisters) Ella Joyce, Fredro Starr, and R&B singer Keith Sweat; 2007's "Humenetomy"; and 2010's "Ex$pendable". Hicks featured in the HBO television series "Subway Stories" in 1997. Two guest roles followed: 2002's "100 Centre Street" in the episode titled "Fathers", and a 2003 episode of "Soul Food: The Series" titled "The New Math". Hicks co-starred in the musical stage play Tyler Perry's "Aunt Bam's Place" with Paris Bennett, Cassi Davis, Jeffrey Lewis, and Melonie Daniels. It had a 3-day run beginning August 30, 2011 in Atlanta, Georgia (Cobb Energy Center) and was filmed for a DVD release on June 12, 2012.
6 Career.:Music. In 1995, Hicks signed a deal with Motown Records and released an album titled "This Time". The single "Ooh, Ooh Baby", written by and featuring Missy Elliott, charted on the Billboard R&B singles chart. However, the lead single intended to debut her singing career was "Distant Lover", an uptempo track produced by Teddy Riley. The album did not take off until the second single, "Silly